name: my_python_env
channels:
  - knime
  - conda-forge
dependencies:
  - python=3.11
  - asttokens=2.4.1
  - authlib=1.3.0
  - aws-c-auth=0.7.8
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.10
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.15
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.10.0
  - aws-c-s3=0.4.6
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.25.0
  - aws-sdk-cpp=1.11.210
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cryptography=42.0.8
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - knime-extension=5.2.0
  - knime-python-base=5.2.4
  - krb5=1.21.2
  - libabseil=20230802.1
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - liblapack=3.9.0
  - libparquet=14.0.1
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libutf8proc=2.8.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.6
  - matplotlib-inline=0.1.7
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.6.0
  - nomkl=1.0
  - numpy=1.26.4
  - openssl=3.3.1
  - orc=1.9.2
  - packaging=24.0
  - pandas=2.0.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.46
  - psutil=5.9.8
  - pure_eval=0.2.2
  - py4j=0.10.9.7
  - pyarrow=14.0.1
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=306
  - pyzmq=26.0.3
  - re2=2023.09.01
  - requests=2.32.3
  - setuptools=70.0.0
  - simple-salesforce=1.10.1
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.3
  - typing_extensions=4.12.1
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33135
  - vs2015_runtime=14.38.33135
  - wcwidth=0.2.13
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.6
